"""initial migration: create all tables

Revision ID: 07751bb666b2
Revises: 
Create Date: 2026-08-12 17:10:04.184627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07751bb666b2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_number', sa.String(), nullable=False),
    sa.Column('building', sa.String(), nullable=False),
    sa.Column('apartment_number', sa.String(), nullable=False),
    sa.Column('room_type', sa.Enum('private', 'double', 'triple', 'quad', name='roomtype'), nullable=False),
    sa.Column('is_occupied', sa.Boolean(), nullable=True),
    sa.Column('is_rent_ready', sa.Boolean(), nullable=True),
    sa.Column('room_issues', sa.Text(), nullable=True),
    sa.Column('maintenance_status', sa.Enum('not_applicable', 'pending_escalation', 'escalated', 'work_assigned', 'work_in_progress', 'completed', 'rent_ready', name='maintenancestatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('building', 'room_number', name='uq_building_room')
    )
    op.create_index(op.f('ix_rooms_id'), 'rooms', ['id'], unique=False)
    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('gender', sa.Enum('male', 'female', 'other', name='gender'), nullable=True),
    sa.Column('intake_date', sa.Date(), nullable=True),
    sa.Column('is_allocated', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_students_id'), 'students', ['id'], unique=False)
    op.create_index(op.f('ix_students_student_id'), 'students', ['student_id'], unique=True)
    op.create_table('requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('requested_roommate_1', sa.Integer(), nullable=True),
    sa.Column('requested_roommate_2', sa.Integer(), nullable=True),
    sa.Column('requested_roommate_3', sa.Integer(), nullable=True),
    sa.Column('request_type', sa.Enum('application', 'room_change', name='requesttype'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'processing', 'completed', 'rejected', 'cancelled', 'on_hold', name='requeststatus'), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('outcome_notes', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['requested_roommate_1'], ['students.id'], ),
    sa.ForeignKeyConstraint(['requested_roommate_2'], ['students.id'], ),
    sa.ForeignKeyConstraint(['requested_roommate_3'], ['students.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_requests_id'), 'requests', ['id'], unique=False)
    op.create_table('student_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('requested_roommate_1', sa.Integer(), nullable=True),
    sa.Column('requested_roommate_2', sa.Integer(), nullable=True),
    sa.Column('requested_roommate_3', sa.Integer(), nullable=True),
    sa.Column('sleep_schedule', sa.Enum('early_bird', 'night_owl', name='sleepschedule'), nullable=False),
    sa.Column('noise_tolerance', sa.Integer(), nullable=False),
    sa.Column('cleanliness', sa.Integer(), nullable=False),
    sa.Column('study_habits', sa.Enum('quiet', 'group', name='studyhabits'), nullable=False),
    sa.Column('diet', sa.Enum('vegetarian', 'non_vegetarian', 'vegan', name='diet'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['requested_roommate_1'], ['students.id'], ),
    sa.ForeignKeyConstraint(['requested_roommate_2'], ['students.id'], ),
    sa.ForeignKeyConstraint(['requested_roommate_3'], ['students.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id')
    )
    op.create_index(op.f('ix_student_preferences_id'), 'student_preferences', ['id'], unique=False)
    op.create_table('allocations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'allocated', 'reallocated', 'unresolved', name='allocationstatus'), nullable=True),
    sa.Column('compatibility_score', sa.Float(), nullable=True),
    sa.Column('is_reallocated', sa.Boolean(), nullable=True),
    sa.Column('allocated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['request_id'], ['requests.id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_allocations_id'), 'allocations', ['id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.Enum('too_early', 'waiting_for_group', 'group_unavailable', 'allocated', 'unresolved', name='notificationtype'), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_email_sent', sa.Enum('pending', 'sent', 'failed', name='emailstatus'), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['request_id'], ['requests.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_allocations_id'), table_name='allocations')
    op.drop_table('allocations')
    op.drop_index(op.f('ix_student_preferences_id'), table_name='student_preferences')
    op.drop_table('student_preferences')
    op.drop_index(op.f('ix_requests_id'), table_name='requests')
    op.drop_table('requests')
    op.drop_index(op.f('ix_students_student_id'), table_name='students')
    op.drop_index(op.f('ix_students_id'), table_name='students')
    op.drop_table('students')
    op.drop_index(op.f('ix_rooms_id'), table_name='rooms')
    op.drop_table('rooms')
    # ### end Alembic commands ###
